[package]
name = "visuara-client"
version.workspace = true
edition.workspace = true

[dependencies]
serde.workspace = true
tokio.workspace = true
visuara-common = { path = "../visuara-common" }
visuara-agent = { path = "../visuara-agent" }
webrtc = "0.17.1"
tokio-tungstenite = "0.30.0"
futures-util = "0.3.32"
anyhow = "1.0.103"
bytes = "1.12.1"
uuid = { version = "1.23.5", features = ["v4"] }
serde_json.workspace = true
clap = { version = "4.6.1", features = ["derive"] }
rtp = "0.17.1"
webrtc-media = "0.17.1"
image = "0.25.10"
eframe = "0.35.0"
egui = "0.35.0"
dirs = "6.0.0"

[dev-dependencies]
axum = "0.8.9"
dashmap = "6.2.1"
visuara-signaling = { path = "../visuara-signaling" }
